language: csharp
dist: xenial
solution: Wallee.sln
git:
    quiet: true
install:
    - nuget restore Wallee.sln
    - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
    - msbuild /t:restore Wallee.sln
    - msbuild Wallee.sln /t:build /p:Configuration=Release
    - mono testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/Wallee.Test/bin/Release/net452/Wallee.Test.dll --inprocess
    - nuget push ./src/Wallee/bin/Release/Wallee.2.0.5.nupkg -Source nuget.org -ApiKey $NUGET_API_KEY_WALLEE  -Verbosity detailed -SkipDuplicate
